## template: jinja
#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false

disable_root: false

hostname: proxmox
fqdn: proxmox.local

# We don't want the default "admin" Debian user:
users: []

packages:
 - dnsmasq
 - curl

write_files:
  # DHCP server for vmbr0:
  - path: /etc/dnsmasq.conf
    owner: root:root
    permissions: '0644'
    content: |
      interface=vmbr0
      dhcp-range=10.10.10.2,10.10.10.254,12h
      dhcp-option=vmbr0,3,10.10.10.1

# Run every boot:
bootcmd:
  # Replace default 127.0.1.1 IP in /etc/hosts with private IP address
  - sed -i'' 's/^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\([[:space:]]*[{]{fqdn}}\)/{{ ds.meta_data.local_ipv4 }}\1/' /etc/cloud/templates/hosts.debian.tmpl
  # Disable IPv6 so we don't hang forever waiting for DHCPv6
  - sed -i'' -e 's/^\([^#].*inet6.*\)/#\1/' -e 's/^\([^#].*try_dhcp 1.*\)/#\1/' /var/run/network/interfaces.d/* /etc/network/cloud-interfaces-template

# Run only on first boot:
runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - echo "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
  - wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
  - apt update && apt full-upgrade -y
  - echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
  # Install Proxmox VE 8 (keep old config files to prevent grub config being changed):
  - apt install proxmox-ve postfix open-iscsi -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y
  # Configure network interfaces:
  - export LOCAL_NET_INTERFACE=$(ip -o link show | grep $(cloud-init query ds.meta_data.mac) | awk '{print $2}' | sed 's/:$//')
  - |
    echo "
    # Include files from /etc/network/interfaces.d:
    source /etc/network/interfaces.d/*
    
    # Cloud images dynamically generate config fragments for newly
    # attached interfaces. See /etc/udev/rules.d/75-cloud-ifupdown.rules
    # and /etc/network/cloud-ifupdown-helper. Dynamically generated
    # configuration fragments are stored in /run:
    source /run/network/interfaces.d/*
    
    auto vmbr0
    iface vmbr0 inet static
    # NAT network for guests
        address  10.10.10.1/24
        bridge-ports none
        bridge-stp off
        bridge-fd 0
    
        post-up   echo 1 > /proc/sys/net/ipv4/ip_forward
        post-up   iptables -t nat -A POSTROUTING -s '10.10.10.0/24' -o ${LOCAL_NET_INTERFACE} -j MASQUERADE
        post-down iptables -t nat -D POSTROUTING -s '10.10.10.0/24' -o ${LOCAL_NET_INTERFACE} -j MASQUERADE
    
    # auto vmbr1
    # iface vmbr1 inet static
    # # Routed network for guests with manually-allocated secondary private ENI IPs
    #     address 172.x.x.x/29
    #     bridge-ports none
    #     bridge-stp off
    #     bridge-fd 0
    #     
    #     post-up echo 1 > /proc/sys/net/ipv4/ip_forward
    #     post-up echo 1 > /proc/sys/net/ipv4/conf/${LOCAL_NET_INTERFACE}/proxy_arp
    " > /etc/network/interfaces
  - rm -f /etc/network/interfaces.new
  - systemctl restart networking.service
  # Fix SSL certificate issue for PVE 8
  - sleep 10
  - |
    if [ ! -f /etc/pve/local/pve-ssl.pem ]; then
      cd /etc/pve/local
      openssl req -x509 -newkey rsa:4096 -keyout pve-ssl.key -out pve-ssl.pem -days 365 -nodes -subj '/CN=proxmox'
      chown root:www-data pve-ssl.key pve-ssl.pem
      chmod 640 pve-ssl.key pve-ssl.pem
    fi
  # Restart all PVE services
  - systemctl restart pvedaemon pveproxy pvescheduler pvestatd
